### ISSUE TITLE
不知哪边能联系到你

### ISSUE THREAD

**Issue by sun47451685** [JixunMoe/mfcDuDownloadCodeGenerator#1]
我是群晖用户，在docker中搜索到了您的项目。

您在介绍中为安卓提供的方法，超链接貌似失效了。

当我在docker中使用了-p， -s时，手机端其他应用貌似会受影响。
请问docker版还会修复吗，谢谢。

**Comment by JixunMoe** [comment]
请问你说的是哪个项目？

**Comment by sun47451685** [comment]
> 请问你说的是哪个项目？

UnblockNeteaseMusic 群晖docker版。

**Comment by JixunMoe** [comment]
https://github.com/nondanee/UnblockNeteaseMusic

你是说的这个吗？这个项目不是我维护的。
