### ISSUE TITLE
[Feature request] add support 一键秒传

### ISSUE THREAD

**Issue by sum2012** [jixunmoe/mfcDuDownloadCodeGenerator#13]
https://mengzonefire.code.misakanet.cn/rapid-upload-userscript-doc/about-bdlink/

**Comment by jixunmoe** [comment]
> GM_setClipboard(bdlinkPrefix + parseResult.bdcode.toBase64()); // 转换为一键秒传

看来是将所有输出内容转换为 UTF-8 然后 base64 编码。

**Comment by jixunmoe** [comment]
不对啊，这个不是已经有了吗… 生成的时候勾上生成链接即可。
