### ISSUE TITLE
v3.2.0 软件运行时系统 Ctrl+A 快捷键失效

### ISSUE THREAD

**Issue by microka** [jixunmoe/mfcDuDownloadCodeGenerator#14]
OS: Windows 11 21H2 22000.978
v3.2.0 软件运行时系统 Ctrl+A 快捷键失效，只有在软件里按 Ctrl+A 有效。

经测试，v3.1.1也有该问题，退回到v3.0.1才恢复正常。

**Comment by jixunmoe** [comment]
已修正，感谢报告
