### ISSUE TITLE
由于找不到 VCRUNTIME140_1.dll

### ISSUE THREAD

**Issue by Inside-yourself** [jixunmoe/mfcDuDownloadCodeGenerator#15]
由于找不到 VCRUNTIME140_1.dll，无法继续执行代码。重新安装程序可能会解决此问题。 

不知道为什么会提示缺少dll，之前100kb的老版本不会，是什么原因呢

**Comment by jixunmoe** [comment]
可能是因为 Visual Studio 的更新了，用到的运行时也更新了。

你可以更新运行时试试：https://aka.ms/vs/17/release/vc_redist.x64.exe

还不行的话我过两天看看怎么让 GitHub 锁定一个 Visual Studio 版本来自动化编译。

**Comment by jixunmoe** [comment]
https://github.com/jixunmoe/mfcDuDownloadCodeGenerator/releases/tag/v3.2.6
