### ISSUE TITLE
v3.2.6版本复制代码有几率不成功

### ISSUE THREAD

**Issue by microka** [jixunmoe/mfcDuDownloadCodeGenerator#17]
v3.2.1.0以及v3.2.6，生成代码完毕后，点击「复制代码」有几率复制不成功。
其中一个复现的流程如下：首先 win+v 启用剪贴板记录功能，生成代码完毕后点击「复制代码」，然后 win+v 呼出剪贴板，此时若看见复制成功，删除该代码。接着再次在软件窗口中点击「复制代码」，此时再输入 win+v 呼出剪贴板，能看到刚才的复制代码操作并没成功。

**Comment by jixunmoe** [comment]
已修正。请等待 v3.2.7 的构建。

**Comment by jixunmoe** [comment]
构建完成：https://github.com/jixunmoe/mfcDuDownloadCodeGenerator/releases/tag/v3.2.7
