### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by popokcn** [JixunMoe/mfcDuDownloadCodeGenerator#2]
本人就是当年提出115标准码的那个软件作者，刚刚在52pojie上看到大佬这个软件，哈哈，满满的回忆，简直异曲同工啊。

给个建议： 
分隔符用"|"这个，因为以前提出115标准码的时候比较仓储没有仔细研究一些稀奇古怪的情况，后来很多网友反映各种问题，后来发现，有些文件名中带有#，导致存在各种小问题，后来发现|这个符号不会出现在文件名中，而且很多magnet等磁力链也是用|这个做分隔符的。所以建议可以改用|做分隔符。

**Comment by JixunMoe** [comment]
问题不大，软件用正则匹配（文件名在最后面）。缺点就是再加额外的信息的话不太好加。

标准提取码也算是参考了当年 115 的思路了 hhh
