### ISSUE TITLE
[Feature request] 能否提供最后一条提取码不换行选项？

### ISSUE THREAD

**Issue by microka** [jixunmoe/mfcDuDownloadCodeGenerator#23]
当前生成器点击复制代码，最后一条提取码结尾附带了一个换行，明白换行在某些场景下的适用性，但不知能否提供一个选项，让最后一条提取码后不附带换行符？感谢~

**Comment by jixunmoe** [comment]
更改为最后一行不添加换行符。

https://github.com/jixunmoe/mfcDuDownloadCodeGenerator/releases/tag/v3.2.11
