### ISSUE TITLE
使用度盘标准码生成器链接失效，文件不存在

### ISSUE THREAD

**Issue by langhuo77** [jixunmoe/mfcDuDownloadCodeGenerator#3]
近期才出现这种情况，文件已经传到百度网盘了， 且时间也隔了很久，至少十个小时以上，文件也没有被和谐，一开始我以为是计算方面出了错误，我从度盘重新下载原文件后，再次计算链接，得到一模一样的链接

使用V1 V2 均得到秒传MD5不匹配，但文件绝对是原文件
两种提取脚本也都试过了 均不行

**Comment by jixunmoe** [comment]
建议将文件更改后重新上传，也有可能是百度后台计算 MD5 出错。
