### ISSUE TITLE
贴进一些文件会闪退

### ISSUE THREAD

**Issue by greenhat616** [jixunmoe/mfcDuDownloadCodeGenerator#4]
链接: https://pan.baidu.com/s/1WUyjjfP8fNWcP1ODOVtEZw 提取码: 58q8 复制这段内容后打开百度网盘手机App，操作更方便哦 
--来自百度网盘超级会员v2的分享

比如说该文件（png 图片复制进去程序直接闪退了）
有些文件甚至直接拖进去没反应，有点奇怪

系统 Windows 10 Pro x64 20H2

Update：现在又好了：（

**Comment by jixunmoe** [comment]
不清楚什么情况，能正常用就好。
